rectified go version in mod file

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -27,6 +27,16 @@ jobs:
           $env:GOOS="linux"
           $env:GOARCH="amd64"
           go build -o server .
+          
+      - name: Check if Docker username secret exists
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+            echo "DOCKER_USERNAME is missing!"
+            exit 1
+          else
+            echo "DOCKER_USERNAME is set."
+          fi
+        shell: bash
 
       - name: Docker login
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
